### PR TITLE
Updated to final version of documentation

### PR DESCRIPTION
**Pull request by mdipompe**
This version of the documentation should be the last changes needed for the addition of WISE to XDQSO(z)!

### CODE REVIEW

**Comment by jobovy** [comment]
Thanks! Are the tags in the new catalog the same as in the old one? Would be good to state that if it's the case or add a similar README as for the XDQSO catalog.

**Comment by mdipompe** [comment]
Good point - the tags are the same but there are a couple additions over the old one.  I’ll make up a new README file and have Hennawi post it with the catalog, hopefully it doesn’t take too long!

-Mike

**Comment by jobovy** [comment]
Okay, I'll merge this once you put in the README link.

**Comment by mdipompe** [comment]
Done!

**Comment by jobovy** [comment]
Okay, I'll merge it once the link is live. Ping me when it is.

**Comment by mdipompe** [comment]
Ok, the README is live now.  Go ahead an merge the documentation changes, and I’ll test them out.

-Mike

**Comment by jobovy** [comment]
Looks good, I'll merge.

**Comment by mdipompe** [comment]
If I go into the docs/source directory on the xdqso master page, I can see the changes - but if I click on the docs link at the bottom (which takes me to the readthedocs page), the update hasn’t applied there…

-Mike

**Comment by jobovy** [comment]
Not sure why it didn't build automatically (readthedocs seemed to have issues this morning), but I started the build manually and the docs are now up-to-date.

**Comment by mdipompe** [comment]
Yep, looks good from here now too.

I just resubmitted - hopefully it’s a quick acceptance from here (can’t imagine why it wouldn’t be…), and we can post to astro-ph and announce to the SDSS collaboration.

-Mike

**Comment by jobovy** [comment]
Yes, hopefully! Thanks for keeping on top of the code and documentation!

Jo

**Pull request merged**
